language: php

sudo: required

env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi" 
    - FI_SOURCE="https://github.com/fusioninventory/fusioninventory-for-glpi"
    - CS=7.2
    - DBNAME=glpitest
    - secure: Y9sG3lZ3Fn3t5BXvcMJQxWsdSUVQgF4M08E6oouYrRc95HEj3ZwZOqp6Df58u8CQFA0EKJyvCBLn8UicvHGMKAD0RwGLBdSP4Ji9gJRZkyMZi79awSshdva/c8dqVQrRd4asuTNQfcagVJpNDnY8sYusw504JUilK3vFVp+39nNZUkcvT69NGVIlXzgHTYinBkVuqDhf5eVtcLcaESLEshrg+5ZERdm+0KifdJVREzhicJxofnmTl/wBsIP7XiQqspljf2/SxLqreGmWXYXUfqIwIOVtsd9fkZChQCz8USC7P427tH6styRDYuMCtvA9b/T/XacSdKFbuDezff3NbIM3b5BebDyCrOK5MGSOdRUY5RuyZN4R5LjePUE++9QNCUPeDSkfb23v0VfuqXIRAxfdtik517GzFy6O7/e6FU1msVZlGQED7Uek9nqnupj+0lIq+99Jcm1UCNJu1NTL2Tv80XXqySaxyE4Sedq/FiYAsy1bo2cg2367I2b4FhFXaJCKkFHcdjHXAeurkRy/brSPhBNoOO5/GA3RepUErgly4P8TLZqHNZv8rgMUoQ88sdwDyXG7dY4UwWiTlCkxMBTqBqJanlTMA9zn2bYyMDioTGnA7+VYAA8cddjFOMVrmmuFJ+YV2x1+5B5qd+Wt8RPwcPQDyqaiN5amb1HGeMA=
  matrix:
    - GLPI_BRANCH=9.2.1 FI_BRANCH=glpi9.2+1.0
    - GLPI_BRANCH=9.2/bugfixes FI_BRANCH=glpi9.2+1.0
    - GLPI_BRANCH=master FI_BRANCH=master

php: 
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - php: nightly

before_install:
  - "./tests/before_install.sh"
      
before_script:
- "./tests/before_script.sh"
script:
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-install -ncc
  - php scripts/mqtt.php --tests > /dev/null 2>&1 &
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-unit --nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-integration --nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-uninstall --ncc
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ]] && [ "$GLPI_BRANCH" = "9.2/bugfixes" ]; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ *.php install/ inc/ front/ ajax/ tests/; fi

after_success:
  # let's update the documentation
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ] && [ "$GLPI_BRANCH" = "9.2/bugfixes" ]; then .github/push_ghpages.sh; fi

cache:
  directories:
  - "$HOME/.composer/cache"
notifications:
  webhooks: https://hooks.aethonan.pro/travisci/-1001061475099/
