language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  global:
    - FUSION_SOURCE=https://github.com/fusioninventory/fusioninventory-for-glpi -b glpi9.1+1.1
  matrix:
    - GLPI_SOURCE=https://github.com/flyve-mdm/glpi -b 9.1.1-backport

before_script:
  - git clone $GLPI_SOURCE ../glpi && cd ../glpi
  - composer install --no-dev
  - php tools/cliinstall.php --db=glpi-test --user=travis --tests
  - mkdir plugins/fusioninventory && git clone $FUSION_SOURCE plugins/fusioninventory
  - mv ../flyve-mdm-glpi plugins/storkmdm
  - cd plugins/storkmdm && composer install
  - cd ../..

script:
  - cd plugins/storkmdm
  - php -S localhost:8088 -t ../.. ../../tests/router.php &>/dev/null &
  - phpunit --verbose
  - vendor/bin/phpcs -p --standard=tools/phpcs-rules.xml *.php install/ inc/ front/ ajax/ tests/

notifications:
  webhooks:
    urls:
      - https://integram.org/ckNa3mjYlqw
    on_success: always
    on_failure: always
    on_start: always
