language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - git clone https://github.com/glpi-project/glpi -b 9.1.1 ../glpi && cd ../glpi
  - composer install --no-dev
  - php tools/cliinstall.php --db=glpi-test --user=travis --tests
  - mkdir plugins/fusioninventory && git clone https://github.com/fusioninventory/fusioninventory-for-glpi -b glpi9.1+1.0 plugins/fusioninventory
  - mv ../flyve-mdm-glpi plugins/storkmdm
  - cd plugins/storkmdm && composer install
  - cd ../..

script:
  - cd plugins/storkmdm
  - php scripts/cli_install.php --tests
  - phpunit --debug --testsuite Install

